FROM golang:1.26.5-alpine AS build

WORKDIR /src
COPY . .

RUN CGO_ENABLED=0 go build -o /out/predictor ./cmd/predictor

FROM alpine:3.22

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=build /out/predictor ./predictor

EXPOSE 8080
ENV APP_VERSION=local

ENTRYPOINT ["./predictor"]
